const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const ROOT=__dirname,DATA=process.env.DATA_FILE||path.join(ROOT,'data.json'),PUBLIC=path.join(ROOT,'public');
const envFile=path.join(ROOT,'.env');
if(fs.existsSync(envFile))fs.readFileSync(envFile,'utf8').split(/\r?\n/).forEach(line=>{const m=line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/);if(m&&!process.env[m[1]])process.env[m[1]]=m[2].replace(/^['"]|['"]$/g,'')});
const tokens=new Map(),id=p=>p+crypto.randomBytes(9).toString('hex');
function normalize(d){for(const k of ['users','links','invitations','sessions','goals','journal','messages'])if(!Array.isArray(d[k]))d[k]=[];return d}
const read=()=>normalize(JSON.parse(fs.readFileSync(DATA,'utf8'))),write=d=>fs.writeFileSync(DATA,JSON.stringify(d,null,2));
const send=(res,status,data,type='application/json')=>{res.writeHead(status,{'Content-Type':type,'Cache-Control':'no-store','X-Content-Type-Options':'nosniff'});res.end(type==='application/json'?JSON.stringify(data):data)};
const body=req=>new Promise((ok,no)=>{let b='';req.on('data',c=>{b+=c;if(b.length>1e6)req.destroy()});req.on('end',()=>{try{ok(b?JSON.parse(b):{})}catch(e){no(e)}})});
function safeUser(u){if(!u)return null;const {password,passwordHash,...safe}=u;return safe}
function passwordHash(p,salt=crypto.randomBytes(16).toString('hex')){return `scrypt$${salt}$${crypto.scryptSync(String(p),salt,64).toString('hex')}`}
function passwordOK(user,p){if(user.passwordHash){const [,salt,hash]=user.passwordHash.split('$'),test=crypto.scryptSync(String(p),salt,64);return hash&&crypto.timingSafeEqual(Buffer.from(hash,'hex'),test)}return user.password===p}
function authId(req){return tokens.get((req.headers.authorization||'').replace('Bearer ',''))}
function factual(text){return /\b(what is|what are|when did|where is|who is|how many|current|latest|law|legal|statistic|study|research|medication|diagnos|tax|court|government|evidence|source|verify)\b/i.test(text)}
function fallbackReply(text,mode){
 const t=text.toLowerCase(),short=text.replace(/\s+/g,' ').trim().slice(0,120),prefix=mode==='joint'?'I want to hold both perspectives here. ':'';
 if(/(suicid|kill myself|hurt myself|not safe)/.test(t))return 'I can’t assess your safety through this app. If you may act now, contact emergency services or call or text 988 in the U.S. Please move near another person if you can.';
 if(/(hit|abuse|violent|afraid|threat)/.test(t))return 'I can’t assess danger through this app. If you may be unsafe, contact emergency services or a trusted local support resource. In the U.S., the National Domestic Violence Hotline is 800-799-SAFE.';
 if(factual(text))return `I can’t verify a current factual answer to “${short}” without the research service connected, and I don’t want to guess. Add the OpenAI text/research key or check an authoritative primary source.`;
 const topic=(text.match(/(?:about|because|when)\s+([^.!?]+)/i)||[])[1];
 if(/angry|mad|fight|argument|yell/.test(t))return prefix+`You described ${topic?`a conflict around ${topic.trim()}`:'a conflict that brought up anger'}. Before deciding what to do, what felt most threatened in that moment—respect, trust, closeness, or fairness?`;
 if(/trust|cheat|betray|affair/.test(t))return prefix+`What you shared about “${short}” points to a trust injury. What is one concrete action—not a promise—that would make the next week feel more predictable?`;
 if(/listen|heard|understand/.test(t))return prefix+`The part I’m hearing is: “${short}” Try reflecting the meaning before solving it. What do you most want your partner to understand about why this mattered?`;
 if(/boundary|space|alone|break/.test(t))return prefix+`You’re asking for space without losing connection. Name the length of the pause and the exact return time; what timing would feel realistic rather than punitive?`;
 if(/sad|lonely|hurt|tired/.test(t))return prefix+`When you say “${short},” it sounds like there is a need underneath the hurt. If you could ask for one specific thing without apologizing, what would it be?`;
 return prefix+`You said, “${short}.” What did that moment mean to you, and what small change would help you feel understood now?`;
}
function outputText(j){if(j.output_text)return j.output_text;return (j.output||[]).flatMap(o=>o.content||[]).map(c=>c.text||'').filter(Boolean).join('\n')}
async function groundedReply(text,mode,recent){
 if(!process.env.OPENAI_API_KEY)return fallbackReply(text,mode);
 const isFact=factual(text),instructions=`You are Sage, an AI relationship-guidance companion, not a licensed professional. Write an original response grounded in the exact recent conversation. Never invent a fact, memory, diagnosis, quote, source, or certainty. Ask one useful question at a time. Keep spoken replies to 2-5 sentences. ${mode==='joint'?'Represent both partners fairly and never assume which person is correct.':'Do not expose private content to a partner.'} ${isFact?'Research the user question. Prefer current primary or authoritative sources, include readable source links, distinguish guidance from verified facts, and explicitly say when evidence is insufficient.':''}`;
 const payload={model:process.env.OPENAI_TEXT_MODEL||'gpt-5.6',instructions,input:[...recent.slice(-8).map(x=>({role:x.role==='sage'?'assistant':'user',content:x.text})),{role:'user',content:text}]};
 if(isFact){payload.tools=[{type:'web_search'}];payload.tool_choice='auto';payload.include=['web_search_call.action.sources']}
 try{const r=await fetch('https://api.openai.com/v1/responses',{method:'POST',headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,'Content-Type':'application/json'},body:JSON.stringify(payload)}),j=await r.json();if(!r.ok)throw Error(j.error?.message||'Response service failed');return outputText(j).trim()||fallbackReply(text,mode)}catch(e){console.error('Grounded response error:',e.message);return fallbackReply(text,mode)}
}
const server=http.createServer(async(req,res)=>{try{
 const url=new URL(req.url,'http://x'),p=url.pathname,m=req.method;
 if(p==='/api/login'&&m==='POST'){const b=await body(req),d=read(),user=d.users.find(x=>x.email.toLowerCase()===String(b.email).toLowerCase());if(!user||!passwordOK(user,b.password))return send(res,401,{error:'Email or password is incorrect'});if(!user.passwordHash){user.passwordHash=passwordHash(b.password);delete user.password;write(d)}const token=crypto.randomBytes(24).toString('hex');tokens.set(token,user.id);return send(res,200,{token,user:safeUser(user)})}
 if(p==='/api/register'&&m==='POST'){const b=await body(req),d=read();if(!b.name||!b.email||String(b.password).length<8)return send(res,400,{error:'Name, email, and an 8-character password are required'});if(d.users.some(x=>x.email.toLowerCase()===String(b.email).toLowerCase()))return send(res,409,{error:'An account already exists'});const user={id:id('u'),name:String(b.name).trim(),email:String(b.email).trim().toLowerCase(),passwordHash:passwordHash(b.password),partnerId:null,avatar:String(b.name).trim()[0].toUpperCase(),createdAt:new Date().toISOString()};d.users.push(user);write(d);const token=crypto.randomBytes(24).toString('hex');tokens.set(token,user.id);return send(res,201,{token,user:safeUser(user)})}
 const uid=authId(req);if(p.startsWith('/api/')&&!uid)return send(res,401,{error:'Please sign in'});const d=read(),me=d.users.find(x=>x.id===uid);if(p.startsWith('/api/')&&!me)return send(res,401,{error:'Please sign in'});
 if(p==='/api/bootstrap'){const partner=d.users.find(x=>x.id===me.partnerId);return send(res,200,{user:safeUser(me),partner:safeUser(partner),sessions:d.sessions.filter(x=>x.participants?.includes(me.id)||x.ownerId===me.id),goals:d.goals.filter(x=>x.ownerId===me.id),journal:d.journal.filter(x=>x.ownerId===me.id),pendingInvites:d.invitations.filter(x=>x.status==='pending'&&(x.inviterId===me.id||x.inviteeId===me.id)).map(x=>({...x,inviter:safeUser(d.users.find(u=>u.id===x.inviterId)),invitee:safeUser(d.users.find(u=>u.id===x.inviteeId))}))})}
 if(p==='/api/realtime-transcription-token'&&m==='POST'){if(!process.env.OPENAI_API_KEY)return send(res,503,{error:'OpenAI Realtime transcription is not configured. Add OPENAI_API_KEY to .env.'});const safetyId=crypto.createHash('sha256').update('sage:'+me.id).digest('hex'),upstream=await fetch('https://api.openai.com/v1/realtime/client_secrets',{method:'POST',headers:{Authorization:`Bearer ${process.env.OPENAI_API_KEY}`,'Content-Type':'application/json','OpenAI-Safety-Identifier':safetyId},body:JSON.stringify({expires_after:{anchor:'created_at',seconds:600},session:{type:'transcription',audio:{input:{noise_reduction:{type:'near_field'},transcription:{model:'gpt-live-transcribe',language:'en',prompt:'A private relationship conversation. Preserve names, punctuation, and exact meaning.'},turn_detection:{type:'server_vad',threshold:.5,prefix_padding_ms:300,silence_duration_ms:700}}}}})}),result=await upstream.json();return upstream.ok?send(res,200,result):send(res,upstream.status,{error:result.error?.message||'Could not start realtime transcription'})}
 if(p==='/api/cartesia-token'&&m==='POST'){if(!process.env.CARTESIA_API_KEY||!process.env.CARTESIA_VOICE_ID)return send(res,503,{error:'Cartesia is not configured. Add CARTESIA_API_KEY and CARTESIA_VOICE_ID to .env.'});const upstream=await fetch('https://api.cartesia.ai/access-token',{method:'POST',headers:{Authorization:`Bearer ${process.env.CARTESIA_API_KEY}`,'Content-Type':'application/json','Cartesia-Version':'2026-03-01'},body:JSON.stringify({grants:{tts:true,stt:false,agent:false},expires_in:600})}),result=await upstream.json();return upstream.ok?send(res,200,{token:result.token,voiceId:process.env.CARTESIA_VOICE_ID,model:process.env.CARTESIA_MODEL||'sonic-3.5',version:'2026-03-01'}):send(res,upstream.status,{error:result.message||result.error||'Could not start Cartesia voice'})}
 if(p==='/api/chat'&&m==='POST'){const b=await body(req);if(!String(b.text||'').trim())return send(res,400,{error:'A message is required'});const mode=b.mode==='joint'?'joint':'solo',recent=d.messages.filter(x=>x.ownerId===me.id&&x.mode===mode),msg={id:id('m'),ownerId:me.id,mode,role:'user',text:String(b.text).trim(),createdAt:new Date().toISOString()};d.messages.push(msg);const reply={id:id('m'),ownerId:me.id,mode,role:'sage',text:await groundedReply(msg.text,mode,recent),createdAt:new Date().toISOString()};d.messages.push(reply);write(d);return send(res,200,{reply,researched:factual(msg.text)&&!!process.env.OPENAI_API_KEY})}
 if(p==='/api/invitations'&&m==='POST'||p==='/api/link'&&m==='POST'){if(me.partnerId)return send(res,409,{error:'Your account is already linked'});const b=await body(req),other=b.email?d.users.find(x=>x.email.toLowerCase()===String(b.email).toLowerCase()):null;if(b.email&&(!other||other.id===me.id))return send(res,404,{error:'No eligible account found'});if(other?.partnerId)return send(res,409,{error:'That account is already linked'});d.invitations.filter(x=>x.inviterId===me.id&&x.status==='pending').forEach(x=>x.status='replaced');const invite={id:id('i'),code:crypto.randomBytes(18).toString('base64url'),inviterId:me.id,inviteeId:other?.id||null,status:'pending',createdAt:new Date().toISOString(),expiresAt:new Date(Date.now()+7*864e5).toISOString()};d.invitations.push(invite);write(d);return send(res,202,{invitation:{...invite,invitee:safeUser(other)}})}
 const inviteMatch=p.match(/^\/api\/invitations\/([^/]+)(?:\/(accept|decline))?$/);if(inviteMatch){const inv=d.invitations.find(x=>x.code===inviteMatch[1]);if(!inv)return send(res,404,{error:'Invitation not found'});if(m==='GET'){return send(res,200,{invitation:{status:inv.status,expiresAt:inv.expiresAt,inviter:safeUser(d.users.find(x=>x.id===inv.inviterId)),forYou:!inv.inviteeId||inv.inviteeId===me.id}})}if(m==='POST'&&inviteMatch[2]){if(inv.status!=='pending'||new Date(inv.expiresAt)<=new Date())return send(res,410,{error:'Invitation is no longer active'});if(inv.inviteeId&&inv.inviteeId!==me.id)return send(res,403,{error:'This invitation belongs to another account'});if(inv.inviterId===me.id)return send(res,400,{error:'You cannot accept your own invitation'});const inviter=d.users.find(x=>x.id===inv.inviterId);if(!inviter||inviter.partnerId||me.partnerId)return send(res,409,{error:'One of these accounts is already linked'});if(inviteMatch[2]==='decline'){inv.status='declined';write(d);return send(res,200,{ok:true})}inv.status='accepted';inv.inviteeId=me.id;inv.acceptedAt=new Date().toISOString();inviter.partnerId=me.id;me.partnerId=inviter.id;d.links.push({id:id('l'),userA:inviter.id,userB:me.id,status:'linked',linkedAt:inv.acceptedAt});write(d);return send(res,200,{partner:safeUser(inviter)})}}
 if(p==='/api/unlink'&&m==='POST'){if(me.partnerId){const other=d.users.find(x=>x.id===me.partnerId);if(other&&other.partnerId===me.id)other.partnerId=null;me.partnerId=null;d.links.filter(x=>x.status==='linked'&&(x.userA===me.id||x.userB===me.id)).forEach(x=>{x.status='unlinked';x.unlinkedAt=new Date().toISOString()});write(d)}return send(res,200,{ok:true})}
 const match=p.match(/^\/api\/(sessions|goals|journal)(?:\/([^/]+))?$/);if(match){const [,kind,itemId]=match,arr=d[kind];if(m==='POST'&&!itemId){const b=await body(req);if(kind==='sessions'&&b.type==='joint'&&!me.partnerId)return send(res,409,{error:'Link a partner before creating a joint session'});const item={...b,id:id(kind[0]),ownerId:me.id,createdAt:new Date().toISOString()};if(kind==='sessions')item.participants=b.type==='joint'?[me.id,me.partnerId]:[me.id];arr.push(item);write(d);return send(res,201,{item})}const item=arr.find(x=>x.id===itemId&&x.ownerId===me.id);if(!item)return send(res,404,{error:'Not found'});if(m==='PUT'){const changes=await body(req);if(kind==='sessions'&&changes.type==='joint'&&!me.partnerId)return send(res,409,{error:'Link a partner before creating a joint session'});Object.assign(item,changes,{id:item.id,ownerId:item.ownerId});if(kind==='sessions'&&changes.type)item.participants=changes.type==='joint'?[me.id,me.partnerId]:[me.id];write(d);return send(res,200,{item})}if(m==='DELETE'){d[kind]=arr.filter(x=>x.id!==itemId);write(d);return send(res,200,{ok:true})}}
 if(p.startsWith('/api/'))return send(res,404,{error:'Not found'});
 let file=p==='/'?'index.html':p.slice(1);file=path.normalize(file).replace(/^\.\.(\/|\\)/,'');let fp=path.join(PUBLIC,file);if(!fp.startsWith(PUBLIC)||!fs.existsSync(fp)||fs.statSync(fp).isDirectory())fp=path.join(PUBLIC,'index.html');const types={'.html':'text/html','.css':'text/css','.js':'application/javascript','.png':'image/png','.svg':'image/svg+xml'};return send(res,200,fs.readFileSync(fp),types[path.extname(fp)]||'application/octet-stream');
}catch(e){console.error(e);send(res,500,{error:'Something went wrong'})}});
const PORT=process.env.PORT||3000;server.listen(PORT,'0.0.0.0',()=>console.log(`Sage listening on http://0.0.0.0:${PORT}`));